#!/bin/bash

export TERM=alacritty
export EDITOR=vim

export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1
export QT_QPA_PLATFORM=wayland
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_DESKTOP=sway
export QT_SCREEN_SCALE_FACTORS="1;1"
export MOZ_ENABLE_WAYLAND=1
export ELECTRON_OZONE_PLATFORM_HINT=auto

if [ "$1" == "e" ]; then
    exec sway --unsupported-gpu -c ~/.config/sway/extern
elif [ "$1" == "s" ]; then
    exec sway --unsupported-gpu -c ~/.config/sway/single
else
    exec sway --unsupported-gpu -c ~/.config/sway/multi
fi
