#!/bin/bash

export TERM=alacritty
export EDITOR=vim

export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1
export QT_QPA_PLATFORM=wayland
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_DESKTOP=sway
export QT_SCREEN_SCALE_FACTORS="1;1"
export MOZ_ENABLE_WAYLAND=1
export ELECTRON_OZONE_PLATFORM_HINT=auto

DP2="/sys/class/drm/card1-DP-2/status"

if [ -f "$DP2" ] && [ "$(cat "$DP2")" == "connected" ]; then
    exec sway --unsupported-gpu -c ~/.config/sway/multi
elif [ "$1" == "s" ]; then
    exec sway --unsupported-gpu -c ~/.config/sway/single
fi
